substitutions:
  restore_mode_light: RESTORE_DEFAULT_OFF
  project_name: "Athom.BR30_ESP8266_PWM_RGBCT_Bulb"
  project_version: "0.0.1"
  hardware_info: "Athom BR30 ESP8266 PWM RGBCT Bulb"

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  rgbct_light: !include ../../light/rgbct.yaml

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_brightness
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_temperature
    inverted: true
    pin: GPIO13
