substitutions:
  project_name: "Dogain.4in_Recessed_WB2S_PWM_RGBWW_Bulb"
  project_version: "0.0.1"
  hardware_info: "Dogain 4in Recessed WB2S PWM RGBWW Bulb"

bk72xx:
  board: wb2s

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIO8
  - platform: libretiny_pwm
    id: output_green
    pin: GPIO7
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIO6
  - platform: libretiny_pwm
    id: output_warm_white
    pin: GPIO24
  - platform: libretiny_pwm
    id: output_cold_white
    pin: GPIO26
