substitutions:
  project_name: "DoHome.G25_ESP32-C3-C05_BP5758D_RGBWW_Bulb"
  project_version: "0.0.1"
  hardware_info: "DoHome G25 ESP32-C3-C05 BP5758D RGBWW Bulb"

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  rgbww_light: !include ../../light/rgbww.yaml

bp5758d:
  data_pin: GPIO3
  clock_pin: GPIO5

# Individual outputs
output:
  - platform: bp5758d
    id: output_red
    channel: 2 # Valid channels are 1-5
    current: 10 # In mA, valid values are 0-90, default is 10.
  - platform: bp5758d
    id: output_green
    channel: 3 # Valid channels are 1-5
    current: 10 # In mA, valid values are 0-90, default is 10.
  - platform: bp5758d
    id: output_blue
    channel: 1 # Valid channels are 1-5
    current: 10 # In mA, valid values are 0-90, default is 10.
  - platform: bp5758d
    id: output_cold_white
    channel: 5 # Valid channels are 1-5
    current: 10 # In mA, valid values are 0-90, default is 10.
  - platform: bp5758d
    id: output_warm_white
    channel: 4 # Valid channels are 1-5
    current: 10 # In mA, valid values are 0-90, default is 10.
