substitutions:
  project_name: "EarthBulb.A19_SM2135_RGBWW_Bulb"
  project_version: "0.0.1"
  hardware_info: "EarthBulb WB8P SM2135 RGBWW Bulb"

bk72xx:
  board: generic-bk7231t-qfn32-tuya

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

sm2135:
  clock_pin: GPIO7
  data_pin: GPIO8
  rgb_current: 10mA
  cw_current: 60mA

output:
  - platform: sm2135
    id: output_red
    channel: 2
  - platform: sm2135
    id: output_green
    channel: 0
  - platform: sm2135
    id: output_blue
    channel: 1
  - platform: sm2135
    id: output_cold_white
    channel: 3
  - platform: sm2135
    id: output_warm_white
    channel: 4
