substitutions:
  project_name: "Hykolity.Recessed_WB3L_PWM_RGBWW_Bulb"
  project_version: "0.0.1"
  hardware_info: "Hykolity Recessed WB3L PWM RGBWW Bulb"

bk72xx:
  board: generic-bk7231t-qfn32-tuya

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIO26
    frequency: 5000hz
  - platform: libretiny_pwm
    id: output_green
    pin: GPIO24
    frequency: 5000hz
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIO6
    frequency: 5000hz
  - platform: libretiny_pwm
    id: output_cold_white
    pin: GPIO9
    frequency: 5000hz
  - platform: libretiny_pwm
    id: output_warm_white
    pin: GPIO8
    frequency: 5000hz

remote_receiver:
  pin:
    number: GPIO1
    inverted: true
    mode: INPUT_PULLUP
  # dump: all