substitutions:
  project_name: "Khsuin.A15_CoB_BK7231N_BP1658CJ_RGBWW_Bulb"
  project_version: "0.0.1"
  hardware_info: "Khsuin A15 CoB BK7231N BP1658CJ RGBWW Bulb"

bk72xx:
  board: generic-bk7231n-qfn32-tuya # LMA45-BKN-V1.0 CoB module

packages:
  rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

bp1658cj:
  data_pin: GPIO8 #PWM2
  clock_pin: GPIO6 #PWM0
  max_power_color_channels: 5 # Valid values are 0-15, 4 is driver default
  max_power_white_channels: 8 # Valid values are 0-15, 6 is driver default

# Individual outputs
output:
  - platform: bp1658cj
    id: output_red
    channel: 2
  - platform: bp1658cj
    id: output_green
    channel: 1
  - platform: bp1658cj
    id: output_blue
    channel: 0
  - platform: bp1658cj
    id: output_cold_white
    channel: 4
  - platform: bp1658cj
    id: output_warm_white
    channel: 3
