substitutions:
  project_name: "LightingInside.11W_RGBCT_Bulb"
  project_version: "0.0.1"
  hardware_info: "LightingInside 11W RGBCT Bulb"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  rgbww_light: !include ../../light/rgbct.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIO8
  - platform: libretiny_pwm
    id: output_green
    pin: GPIO24
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIO26
  - platform: libretiny_pwm
    id: output_brightness
    pin: GPIO7
  - platform: libretiny_pwm
    id: output_temperature
    pin: GPIO6
    inverted: true
