substitutions:
  project_name: "Lohas.A21_14W_CB2L_PWM_RGBWW_Bulb"
  project_version: "0.0.1"
  hardware_info: "Lohas A21 14W CB2L PWM RGBWW Bulb"

bk72xx:
  board: cb2l

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIO26
  - platform: libretiny_pwm
    id: output_green
    pin: GPIO6
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIO24
  - platform: libretiny_pwm
    id: output_cold_white
    pin: GPIO8
  - platform: libretiny_pwm
    id: output_warm_white
    pin: GPIO7
