substitutions:
  project_name: "Peteme.A19_WB3L_PWM_RGBWW_Bulb"
  project_version: "0.0.1"
  hardware_info: "Peteme A19 WB3L PWM RGBWW Bulb"

bk72xx:
  board: wb3l

packages:
  rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIO8
  - platform: libretiny_pwm
    id: output_green
    pin: GPIO24
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIO26
  - platform: libretiny_pwm
    id: output_cold_white
    pin: GPIO7
  - platform: libretiny_pwm
    id: output_warm_white
    pin: GPIO6
