substitutions:
  project_name: "Schwaiger.A19_CB2L_BP5758D_RGBW_Bulb"
  project_version: "0.0.1"
  hardware_info: "Schwaiger A19 CB2L BP5758D RGBW Bulb"

bk72xx:
  board: cb2l

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  rgbw_warm_light: !include ../../light/rgbw-warm.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

bp5758d:
  data_pin: GPIO8
  clock_pin: GPIO7

# Individual outputs
output:
  - platform: bp5758d
    id: output_red
    channel: 3 # Valid channels are 1-5
    current: 28 # In mA, valid values are 0-90, default is 10.
  - platform: bp5758d
    id: output_green
    channel: 2 # Valid channels are 1-5
    current: 28 # In mA, valid values are 0-90, default is 10.
  - platform: bp5758d
    id: output_blue
    channel: 1 # Valid channels are 1-5
    current: 28 # In mA, valid values are 0-90, default is 10.
  - platform: bp5758d
    id: output_warm_white
    channel: 5 # Valid channels are 1-5
    current: 55 # In mA, valid values are 0-90, default is 10.
