substitutions:
  project_name: "Vont.A19_ESP32-C3_PWM_RGBWW_Bulb"
  project_version: "0.0.1"
  hardware_info: "Vont A19 ESP32-C3 PWM RGBWW Bulb"

esp32:
  variant: ESP32C3
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

esphome:
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3

packages:
  rgbww_light: !include ../../light/rgbww.yaml

output:
 - platform: ledc
   id: output_red
   pin: GPIO6
 - platform: ledc
   id: output_green
   pin: GPIO7
 - platform: ledc
   id: output_blue
   pin: GPIO5
 - platform: ledc
   id: output_brightness
   pin: GPIO4
 - platform: ledc
   id: output_temperature
   inverted: true
   pin: GPIO3
