substitutions:
  device_name: bulb-mud-room2
  friendly_name: Mud Room Bulb 2
  device_group_name: group-mud-room-lights
  area: Mud Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/bulbs/crestin-a19.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml