substitutions:
  device_name: !secret device-name-bulb-basement-hallway
  friendly_name: Basement Hallway Bulb
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: Basement Hallway
  wifi_static_ip: !secret ip-bulb-basement-hallway

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/brillihood-ceiling.yaml
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-basement-hallway1