substitutions:
  device_name: bulb-kitchen5
  friendly_name: Kitchen Bulb 5
  device_group_name: group-kitchen-lights
  area: Kitchen

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/bulbs/teckin-br30.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml