substitutions:
  device_name: !secret device-name-bulb-master-bathroom-vanity1
  friendly_name: Master Bathroom Vanity Bulb 1
  default_white_color_temperature: "2550 K"
  area: Master Bathroom
  wifi_static_ip: !secret ip-bulb-master-bathroom-vanity1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/cree-a19-cb8p.yaml
  udp_groups_sender: !include
    file: common/udp-groups/udp-groups-light-sender5.yaml
    vars:
      address1: !secret ip-bulb-master-bathroom-vanity2
      address2: !secret ip-bulb-master-bathroom-vanity3
      address3: !secret ip-bulb-master-bathroom-vanity4
      address4: !secret ip-bulb-master-bathroom-vanity5
      address5: !secret ip-bulb-master-bathroom-vanity6
