substitutions:
  device_name: !secret device-name-bulb-bar-clock1
  friendly_name: Bar Clock Bulb 1
  area: Bar
  wifi_static_ip: !secret ip-bulb-bar-clock1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/khsuin-a15.yaml
  udp_groups_sender: !include
    file: common/udp-groups/udp-groups-light-sender1.yaml
    vars:
      address1: !secret ip-bulb-bar-clock2
