substitutions:
  device_name: bulb-laundry-room1
  friendly_name: Laundry Room Bulb 1
  device_group_name: group-laundry-room-lights
  area: Laundry Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/bulbs/crestin-a19.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml