substitutions:
  device_name: bulb-utility-room
  friendly_name: Utility Room Bulb
  device_group_name: group-utility-room-lights
  area: Utility Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  device: !include common/devices/bulbs/cree-100w-t.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml
