substitutions:
  device_name: bulb-basement-hallway
  friendly_name: Basement Hallway Bulb
  device_group_name: group-basement-hallway-lights
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: Basement Hallway

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  device: !include common/devices/bulbs/brillihood-ceiling.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml
