substitutions:
  device_name: !secret device-name-bulb-driveway3
  friendly_name: Driveway Bulb 3
  area: Driveway
  wifi_static_ip: !secret ip-bulb-driveway3

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/cree-a21-n.yaml
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-driveway1
