substitutions:
  device_name: !secret device-name-bulb-upper-bathroom-vanity1
  friendly_name: Upper Bathroom Vanity Bulb 1
  default_white_color_temperature: "3000 K"
  area: Upper Bathroom
  wifi_static_ip: !secret ip-bulb-upper-bathroom-vanity1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/cree-a19-wb8p.yaml
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-upper-bathroom-vanity
