substitutions:
  device_name: !secret device-name-bulb-3-season-room-entry
  friendly_name: 3 Season Room Entry Bulb
  area: 3 Season Room Entry
  wifi_static_ip: !secret ip-bulb-3-season-room-entry

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/lohas-a21.yaml
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-3-season-room-entry
