substitutions:
  device_name: bulb-upper-bathroom-overhead
  friendly_name: Upper Bathroom Overhead Light
  device_group_name: group-upper-bathroom-overhead-light
  area: Upper Bathroom

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  device: !include common/devices/bulbs/earthbulb-a19.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml