substitutions:
  device_name: bulb-3-season-room-entry
  friendly_name: 3 Season Room Entry Bulb
  device_group_name: group-3-season-room-entry-lights
  area: 3 Season Room Entry

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/bulbs/lohas-a21.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml
