substitutions:
  device_name: bulb-family-room2
  friendly_name: Family Room Bulb 2
  device_group_name: group-family-room-lights
  area: Family Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  device: !include common/devices/bulbs/helloify-beken-a19.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml
