substitutions:
  device_name: !secret device-name-bulb-half-bathroom3
  friendly_name: Half Bathroom Bulb 3
  default_white_color_temperature: "2500 K"
  area: Half Bathroom
  wifi_static_ip: !secret ip-bulb-half-bathroom3

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/cree-a19-cb8p.yaml
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-half-bathroom
