substitutions:
  device_name: bulb-lower-hallway2
  friendly_name: Lower Hallway Bulb 2
  device_group_name: group-lower-hallway-lights
  area: Lower Hallway

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  device: !include common/devices/bulbs/helloify-beken-a19.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml