substitutions:
  device_name: bulb-porch2
  friendly_name: Porch Bulb 2
  device_group_name: group-porch-lights
  area: Porch

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  device: !include common/devices/bulbs/cree-100w-n.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml
