substitutions:
  device_name: bulb-master-bathroom-shower
  friendly_name: Master Bathroom Shower Bulb
  device_group_name: group-master-bathroom-shower-lights
  area: Master Bathroom

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  device: !include common/devices/bulbs/lohas-a21.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml
