substitutions:
  device_name: !secret device-name-bulb-weavers-room1
  friendly_name: Weaver's Room Bulb 1
  default_white_color_temperature: "2550 K"
  area: Weaver's Room
  wifi_static_ip: !secret ip-bulb-weavers-room1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/cree-a19-cb8p.yaml
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-weavers-room
