substitutions:
  device_name: !secret device-name-bulb-fireplace1
  friendly_name: Fireplace Bulb 1
  area: Fireplace Lights
  wifi_static_ip: !secret ip-bulb-fireplace1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/teckin-br30.yaml
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-fireplace-light
