substitutions:
  device_name: !secret device-name-bulb-kitchen-sink
  friendly_name: Kitchen Sink Bulb
  restore_mode_light: ALWAYS_OFF
  area: Kitchen Sink
  wifi_static_ip: !secret ip-bulb-kitchen-sink

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/bulbs/teckin-br30.yaml
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-kitchen-sink
