substitutions:
  device_name: bulb-lower-bathroom-vanity1
  friendly_name: Lower Bathroom Vanity Bulb 1
  device_group_name: group-lower-bathroom-vanity-lights
  area: Lower Bathroom

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  device: !include common/devices/bulbs/daybetter-n-a19.yaml
  device_groups: !include common/device-groups/device-groups-light-receive-only.yaml