substitutions:
  device_name: !secret device-name-garage-door-main
  id_prefix: garage_door_main
  friendly_name: Main Garage Door
  area: Garage
  wifi_static_ip: !secret ip-garage-door-main

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/garage-doors/ratgdo-esp32-d1-mini.yaml
  #btproxy: !include common/btproxy/btproxy.yaml
