substitutions:
  device_name: !secret device-name-lamp-master-bedroom
  friendly_name: Master Bedroom Lamp
  area: Master Bedroom Lamp
  wifi_static_ip: !secret ip-lamp-master-bedroom

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/lamps/eyesound.yaml
