substitutions:
  device_name: lamp-master-bedroom
  friendly_name: Master Bedroom Lamp
  #device_group_name: group-master-bedroom-lamp
  #use_mac_address: "true"
  area: Master Bedroom Lamp

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  device: !include common/devices/lamps/eyesound.yaml
  #device_groups: !include common/device-groups/device-groups-light.yaml
