substitutions:
  device_name: !secret device-name-nightlight-entry
  friendly_name: Entry Nightlight
  #restore_mode_light: ALWAYS_ON
  area: Entry
  wifi_static_ip: !secret ip-nightlight-entry

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/nightlights/tuya-generic.yaml
