substitutions:
  device_name: !secret device-name-outlet-hobby-room-3d-printer
  friendly_name: Hobby Room 3D Printer Outlet
  restore_mode_relay: RESTORE_DEFAULT_OFF
  area: Hobby Room
  wifi_static_ip: !secret ip-outlet-hobby-room-3d-printer

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/outlets/sonoff-s31.yaml
