substitutions:
  device_name: outlet-laundry-room
  friendly_name: Laundry Room Outlet
  #use_mac_address: "true"
  #device_group_name: group-outlet-laundry-
  area: Laundry Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/outlets/gosund-wo1-in-wall.yaml
  #device_groups: !include common/device-groups/device-groups-light.yaml