substitutions:
  device_name: !secret device-name-outlet-laundry-room
  friendly_name: Laundry Room Outlet
  area: Laundry Room
  wifi_static_ip: !secret ip-outlet-laundry-room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/outlets/gosund-wo1-in-wall.yaml
