substitutions:
  device_name: !secret device-name-outlet-bench
  friendly_name: Bench Outlet
  restore_mode_relay: RESTORE_DEFAULT_OFF
  # current_resistor: "0.0011"
  # voltage_divider: "1450"
  area: Bench
  wifi_static_ip: !secret ip-outlet-bench
  delay: 0.75s

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/outlets/sonoff-s31.yaml

button:
  - platform: template
    name: Cycle 3x
    on_press:
      - repeat:
          count: 3
          then:
            - switch.turn_off: relay
            - delay: ${delay}
            - switch.turn_on: relay
            - delay: ${delay}
  - platform: template
    name: Cycle 4x
    on_press:
      - repeat:
          count: 4
          then:
            - switch.turn_off: relay
            - delay: ${delay}
            - switch.turn_on: relay
            - delay: ${delay}
  - platform: template
    name: Cycle 5x
    on_press:
      - repeat:
          count: 5
          then:
            - switch.turn_off: relay
            - delay: ${delay}
            - switch.turn_on: relay
            - delay: ${delay}
