substitutions:
  device_name: !secret device-name-outlet-tower-fan
  friendly_name: Tower Fan Outlet
  restore_mode_relay: RESTORE_DEFAULT_OFF
  # current_resistor: "0.0011"
  # voltage_divider: "1450"
  area: Master Bedroom
  wifi_static_ip: !secret ip-outlet-tower-fan

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/outlets/sonoff-s31.yaml
