substitutions:
  device_name: !secret device-name-outlet-garage
  friendly_name: Garage Outlet
  restore_mode_relay: RESTORE_DEFAULT_ON
  # current_resistor: 0.0011
  # voltage_divider: 1450
  area: Garage
  wifi_static_ip: !secret ip-outlet-garage

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/outlets/switchbot.yaml
  btproxy: !include common/btproxy/btproxy.yaml
