substitutions:
  device_name: outlet-hobby-room-3d-printer
  friendly_name: Hobby Room 3D Printer Outlet
  restore_mode_relay: RESTORE_DEFAULT_OFF
  #use_mac_address: "true"
  #device_group_name: group-outlet-
  area: Hobby Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  device: !include common/devices/outlets/sonoff-s31.yaml
  #btproxy: !include common/btproxy/btproxy.yaml
  #device_groups: !include common/device-groups/device-groups-switch.yaml
