substitutions:
  device_name: sensor-mmwave1
  friendly_name: mmWave Presence Sensor 1
  #device_group_name: group-master-bedroom-lamp
  #use_mac_address: "true"
  #area: #

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  device: !include common/devices/sensors/mmwave-zg-205w.yaml
  #device_groups: !include common/device-groups/device-groups-light.yaml
