substitutions:
  device_name: sensor-pir-lux
  friendly_name: PIR and Lux Sensor
  #device_group_name: group-master-bedroom-lamp
  #use_mac_address: "true"
  #area: #

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  device: !include common/devices/sensors/tuya-generic-pir-lux.yaml
  #device_groups: !include common/device-groups/device-groups-light.yaml

wifi:
  use_address: 10.4.99.70

api:
  reboot_timeout: 0s