substitutions:
  # sensor-master-bedroom-air-quality exceeds ESPHome's 31 character host limit.
  device_name: !secret device-name-sensor-master-bedroom-air
  friendly_name: Master Bedroom Air Quality
  area: Master Bedroom
  wifi_static_ip: !secret ip-sensor-master-bedroom-air

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/sensors/tuya-generic-vt14in1-air-quality.yaml
