substitutions:
  device_name: switch-entry2
  friendly_name: Entry Light 2
  device_group_name: group-entry-lights
  detach_relay: "true"
  status_light_follows_primary_light_state: "false"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_OFF
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: Entry

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  device: !include common/devices/switches/ultrapro.yaml
  device_groups: !include common/device-groups/device-groups-light.yaml
