substitutions:
  device_name: switch-master-bedroom-closet
  friendly_name: Master Bedroom Closet Light
  device_group_name: group-master-bedroom-closet-light
  detach_relay: "true"
  status_light_follows_primary_light_state: "false"
  status_inverted: "false"
  restore_mode_relay: RESTORE_DEFAULT_ON
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: Master Bedroom Closet

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  #wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  #wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/switches/ultrapro.yaml
  device_groups: !include common/device-groups/device-groups-light.yaml
  #device_groups_base: !include common/device-groups/device-groups-base.yaml

# switch:
#   - platform: template
#     id: switch_template
#     name: Template Switch
#     optimistic: true

# device_groups:
#   - group_name: ${device_group_name}
#     switches:
#       - switch_template
#     # lights:
#     #   - light_primary