substitutions:
  device_name: switch-3-season-room-entry
  friendly_name: 3 Season Room Entry Light
  device_group_name: group-3-season-room-entry-lights
  detach_relay: "true"
  status_light_follows_primary_light_state: "true"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_ON
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: 3 Season Room Entry

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/switches/ultrapro.yaml
  device_groups: !include common/device-groups/device-groups-light-with-status.yaml
