substitutions:
  device_name: !secret device-name-switch-driveway1
  friendly_name: Driveway Light
  detach_relay: "true"
  status_light_follows_primary_light_state: "true"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_ON
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: Driveway
  warm_white_color_temperature: "2200 K"
  default_white_color_temperature: "2200 K"
  wifi_static_ip: !secret ip-switch-driveway1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/switches/ultrapro.yaml
  udp_groups_sender: !include
    file: common/udp-groups/udp-groups-light-sender4.yaml
    vars:
      address1: !secret ip-bulb-driveway1
      address2: !secret ip-bulb-driveway2
      address3: !secret ip-bulb-driveway3
      address4: !secret ip-switch-driveway2
  udp_groups_receive2: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_id: 2
      remote_switch_id: !secret device-name-switch-driveway2

binary_sensor:
  - id: !extend button_on
    on_double_click:
      then:
        - event.trigger:
            id: event_scene_on
            event_type: "scene_on"
  - id: !extend button_off
    on_double_click:
      then:
        - event.trigger:
            id: event_scene_off
            event_type: "scene_off"

event:
  - platform: template
    id: event_scene_on
    name: Scene On
    event_types:
      - "scene_on"
  - platform: template
    id: event_scene_off
    name: Scene Off
    event_types:
      - "scene_off"
