substitutions:
  device_name: "switch-upper-bathroom-vanity"
  friendly_name: Upper Bathroom Vanity Light
  device_group_name_primary: group-upper-bathroom-vanity-lights
  device_group_name_secondary: group-upper-bathroom-overhead-light
  restore_mode_relay1: ALWAYS_ON
  restore_mode_relay2: ALWAYS_OFF
  restore_mode_motion: RESTORE_DEFAULT_ON
  motion_on_time: '120' # time (in seconds) to leave the relay on after motion is sensed
  area: Upper Bathroom

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  device: !include common/devices/switches/motion-double-detached.yaml
  device_groups: !include common/device-groups/device-groups-base.yaml

device_groups:
  - group_name: ${device_group_name_primary}
    lights:
      - light_primary
  - group_name: ${device_group_name_secondary}
    lights:
      - light_secondary
