substitutions:
  device_name: switch-hobby-room
  friendly_name: Hobby Room Light
  device_group_name: group-hobby-room-lights
  detach_relay: "true"
  status_light_follows_primary_light_state: "false"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_ON
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: Hobby Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-upper-mid-lower.yaml
  device: !include common/devices/switches/ultrapro.yaml
  device_groups: !include common/device-groups/device-groups-light.yaml
