substitutions:
  device_name: switch-3-season-room-fan
  friendly_name: 3 Season Room Ceiling Fan
  #device_group_name: group-3-season-room-fan
  restore_mode_fan: RESTORE_DEFAULT_OFF
  area: 3 Season Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/switches/treatlife-ds02f.yaml
  #device_groups: !include common/device-groups/device-groups-light.yaml
