substitutions:
  device_name: switch-3-season-room-light
  friendly_name: 3 Season Room Light
  device_group_name: group-3-season-room-lights
  detach_relay: "true"
  status_light_follows_primary_light_state: "false"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_ON
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: 3 Season Room
  warm_white_color_temperature: "2200 K"
  default_white_color_temperature: "2200 K"

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/switches/ultrapro.yaml
  device_groups: !include common/device-groups/device-groups-light-with-status.yaml
