substitutions:
  device_name: !secret device-name-switch-garage1
  friendly_name: Garage Light
  detach_relay: "false"
  status_light_follows_primary_light_state: "true"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_OFF
  restore_mode_light: ALWAYS_OFF
  area: Garage
  wifi_static_ip: !secret ip-switch-garage1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/switches/ultrapro.yaml
  udp_groups_sender: !include
    file: common/udp-groups/udp-groups-light-sender1.yaml
    vars:
      address1: !secret ip-switch-garage2
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_id: 2
      remote_switch_id: !secret device-name-switch-garage2
