substitutions:
  device_name: !secret device-name-switch-basement-hallway1
  friendly_name: Basement Hallway Light
  restore_mode_relay: ALWAYS_ON
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: Basement Hallway
  ignore_sun: "true"
  wifi_static_ip: !secret ip-switch-basement-hallway1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/switches/motion-single.yaml
  udp_groups_sender: !include
    file: common/udp-groups/udp-groups-light-sender2.yaml
    vars:
      address1: !secret ip-bulb-basement-hallway
      address2: !secret ip-switch-basement-hallway2
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_id: 2
      remote_switch_id: !secret device-name-switch-basement-hallway2