substitutions:
  device_name: !secret device-name-switch-whole-home-fan
  friendly_name: Whole Home Fan
  area: Utility Room
  wifi_static_ip: !secret ip-switch-whole-home-fan

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/switches/tuya-generic-1ch-dry-contact.yaml
