substitutions:
  device_name: switch-garage1
  friendly_name: Garage Light
  device_group_name: group-garage-lights
  detach_relay: "false"
  status_light_follows_primary_light_state: "true"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_OFF
  restore_mode_light: ALWAYS_OFF
  area: Garage

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/switches/ultrapro.yaml
  device_groups: !include common/device-groups/device-groups-light-with-status.yaml
