substitutions:
  device_name: switch-garage2
  friendly_name: Garage Light 2
  device_group_name: group-garage-lights
  restore_mode_relay1: ALWAYS_OFF
  restore_mode_relay2: ALWAYS_OFF
  detach_relay: "true"
  motion_on_time: "120"
  area: Garage

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-lower-mid-upper.yaml
  device: !include common/devices/switches/motion-double.yaml
  device_groups: !include common/device-groups/device-groups-light-with-status.yaml
