substitutions:
  device_name: !secret device-name-switch-living-room2
  friendly_name: Living Room Light 2
  detach_relay: "true"
  status_light_follows_primary_light_state: "false"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_OFF
  restore_mode_light: RESTORE_DEFAULT_OFF
  warm_white_color_temperature: "2200 K"
  default_white_color_temperature: "2550 K"
  area: Living Room
  wifi_static_ip: !secret ip-switch-living-room2

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/switches/ultrapro.yaml
  udp_groups_sender: !include
    file: common/udp-groups/udp-groups-light-sender1.yaml
    vars:
      remote_id: 2
      address1: !secret ip-switch-living-room1
  udp_groups_receive: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_switch_id: !secret device-name-switch-living-room1
