substitutions:
  device_name: !secret device-name-switch-guest-bedroom
  friendly_name: Guest Bedroom Light
  detach_relay: "true"
  status_light_follows_primary_light_state: "false"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_ON
  restore_mode_light: RESTORE_DEFAULT_OFF
  warm_white_color_temperature: "2200 K"
  default_white_color_temperature: "2550 K"
  area: Guest Bedroom
  wifi_static_ip: !secret ip-switch-guest-bedroom

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/switches/ultrapro.yaml
  udp_groups_sender: !include
    file: common/udp-groups/udp-groups-light-sender2.yaml
    vars:
      address1: !secret ip-bulb-guest-bedroom1
      address2: !secret ip-bulb-guest-bedroom2
