substitutions:
  device_name: switch-family-room-light1
  friendly_name: Family Room Light
  device_group_name: group-family-room-lights
  detach_relay: "true"
  status_light_follows_primary_light_state: "false"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_OFF
  restore_mode_light: RESTORE_DEFAULT_OFF
  area: Family Room

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  device: !include common/devices/switches/ultrapro.yaml
  device_groups: !include common/device-groups/device-groups-light.yaml
