substitutions:
  device_name: !secret device-name-switch-lower-hallway1
  friendly_name: Lower Hallway Light
  detach_relay: "true"
  status_light_follows_primary_light_state: "false"
  status_inverted: "false"
  restore_mode_relay: ALWAYS_ON
  restore_mode_light: RESTORE_DEFAULT_OFF
  warm_white_color_temperature: "2200 K"
  default_white_color_temperature: "2550 K"
  area: Lower Hallway
  wifi_static_ip: !secret ip-switch-lower-hallway1

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi/wifi-mid-upper-lower.yaml
  wifi_static_ip: !include common/wifi/wifi-static-ip.yaml
  device: !include common/devices/switches/ultrapro.yaml
  udp_groups_sender: !include
    file: common/udp-groups/udp-groups-light-sender4.yaml
    vars:
      address1: !secret ip-bulb-lower-hallway1
      address2: !secret ip-bulb-lower-hallway2
      address3: !secret ip-switch-lower-hallway2
      address4: !secret ip-switch-lower-hallway3
  udp_groups_receive2: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_id: 2
      remote_switch_id: !secret device-name-switch-lower-hallway2
  udp_groups_receive3: !include
    file: common/udp-groups/udp-groups-light-receiver.yaml
    vars:
      remote_id: 3
      remote_switch_id: !secret device-name-switch-lower-hallway3
