substitutions:
  restore_mode_relay: RESTORE_DEFAULT_ON
  current_res: "0.00255"
  voltage_div: "785"
  # The value 'Power' shows by default is incorrect, to add a linear correction
  # place a known entity and set the calibration data here.
  calibration_pre_cal_power_value: "27.25"
  calibration_expected_correct_value: "60.0"
  project_name: "Dewenwils.WB3S_BL0937_Energy_Monitoring_Plug"
  project_version: "0.0.1"
  hardware_info: "Dewenwils WB2S BL0937 Energy Monitoring Plug"

bk72xx:
  board: wb2s

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

sensor:
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO6
      inverted: true
    cf_pin:
      number: GPIO8
      inverted: true
    cf1_pin:
      number: GPIO7
      inverted: true
    update_interval: 5s
    current:
      name: Current
      icon: mdi:current-ac
      unit_of_measurement: A
      accuracy_decimals: 3
    voltage:
      name: Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
      accuracy_decimals: 3
    power:
      id: wattage
      name: Power
      icon: mdi:flash-outline
      unit_of_measurement: W
      accuracy_decimals: 3
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 0.0 # No load
            - ${calibration_pre_cal_power_value} -> ${calibration_expected_correct_value} # verified expected load
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
  - platform: total_daily_energy
    name: Energy
    icon: mdi:circle-slice-3
    power_id: wattage
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    id: button_primary
    device_class: power
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: Relay
    pin: GPIO24
    id: relay
    restore_mode: ${restore_mode_relay}
    on_turn_on:
      light.turn_on: light_status
    on_turn_off:
      light.turn_off: light_status

light:
  - platform: binary
    id: light_status
    output: output_status_led
    restore_mode: ${restore_mode_relay} # attach to relay state

output:
  - platform: gpio
    id: output_status_led
    pin: GPIO10
    inverted: true
