substitutions:
  project_name: "Gosund.ESP8285_Outlet_Extender"
  project_version: "0.0.1"
  hardware_info: "Gosund ESP8285 Outlet Extender"
  restore_mode_relay1: RESTORE_DEFAULT_ON
  restore_mode_relay2: RESTORE_DEFAULT_ON
  restore_mode_relay3: RESTORE_DEFAULT_ON
  restore_mode_relayUSB: ALWAYS_ON

esp8266:
  board: esp8285
  restore_from_flash: true
  early_pin_init: false

packages:
  device_diagnostics: !include ../device-diagnostics.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT
      inverted: yes
    id: button_toggle
    on_press:
      then:
        - if:
            condition:
              or:
                - switch.is_on: relay1
                - switch.is_on: relay2
                - switch.is_on: relay3
                #- switch.is_on: relayUSB
            then:
              - switch.turn_off: relay1
              - switch.turn_off: relay2
              - switch.turn_off: relay3
              #- switch.turn_off: relayUSB
            else:
              - switch.turn_on: relay1
              - switch.turn_on: relay2
              - switch.turn_on: relay3
              #- switch.turn_on: relayUSB

switch:
  - platform: gpio
    name: Outlet 1
    id: relay1
    pin: GPIO12
    restore_mode: ${restore_mode_relay1}
    on_turn_on:
      - script.execute: update_status
    on_turn_off:
      - script.execute: update_status
  - platform: gpio
    name: Outlet 2
    id: relay2
    pin: GPIO13
    restore_mode: ${restore_mode_relay2}
    on_turn_on:
      - script.execute: update_status
    on_turn_off:
      - script.execute: update_status
  - platform: gpio
    name: Outlet 3
    id: relay3
    pin: GPIO14
    restore_mode: ${restore_mode_relay3}
    on_turn_on:
      - script.execute: update_status
    on_turn_off:
      - script.execute: update_status
  - platform: gpio
    name: USB
    id: relayUSB
    pin:
      number: GPIO5
      inverted: yes
    restore_mode: ${restore_mode_relayUSB}

output:
  - platform: gpio
    id: output_white_led
    pin:
      number: GPIO0
      inverted: true

light:
  - platform: binary
    id: led_relay
    output: output_white_led

status_led:
  pin:
    number: GPIO2
    inverted: true

script:
  - id: update_status
    then:
      - if:
          condition:
            or:
              - switch.is_on: relay1
              - switch.is_on: relay2
              - switch.is_on: relay3
          then:
            light.turn_on: led_relay
          else:
            light.turn_off: led_relay
