substitutions:
  project_name: "SwitchBot.ESP32-C3_BL0937_Energy_Monitoring_Plug"
  project_version: "0.0.1"
  hardware_info: "Switchbot ESP32-C3 BL0937 Energy Monitoring Plug"
  restore_mode_relay: RESTORE_DEFAULT_ON
  current_resistor: "0.0011"
  voltage_divider: "1450"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO20
      inverted: true
    cf_pin: GPIO18
    cf1_pin: GPIO19
    model: BL0937
    current_resistor: ${current_resistor}
    voltage_divider: ${voltage_divider}
    current:
      name: Current
      accuracy_decimals: 1
    voltage:
      name: Voltage
      accuracy_decimals: 1
    power:
      name: Power
      accuracy_decimals: 1
    energy:
      name: Energy
    update_interval: 3s
    change_mode_every: 4

switch:
  - platform: gpio
    name: Relay
    id: relay
    device_class: outlet
    pin: GPIO6
    restore_mode: ${restore_mode_relay}
    on_turn_on:
      then:
        - light.turn_on: light_status
    on_turn_off:
      then:
        - light.turn_off: light_status  

binary_sensor:
  - platform: gpio
    id: button_primary
    internal: true
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: relay 

light:
  - platform: binary
    id: light_status
    output: output_status_led
    restore_mode: ${restore_mode_relay} # attach to relay state

output:
  # White status LED
  - id: output_status_led
    platform: gpio
    pin: GPIO7
    inverted: true

status_led:
  pin:
    number: GPIO8
    inverted: true
