substitutions:
  project_name: "Sylvania.WB2S_75702_Plug"
  project_version: "0.0.1"
  hardware_info: "Sylvania WB2S 75702 Plug"

bk72xx:
  board: wb2s

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO11
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: ""
    pin: GPIO26

status_led:
  pin:
    number: GPIO6
    inverted: true
