substitutions:
  project_name: "Sylvania.WB2S_75702_Plug"
  project_version: "0.0.1"
  hardware_info: "Sylvania WB2S 75702 Plug"
  restore_mode_relay: "ALWAYS_ON"

bk72xx:
  board: wb2s

packages:
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

binary_sensor:
  - platform: gpio
    id: button_relay
    pin:
      number: GPIO11
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: None
    pin: GPIO26
    restore_mode: ${restore_mode_relay}

status_led:
  pin:
    number: GPIO6
    inverted: true
