substitutions:
  project_name: "Tuya_Generic.Custom_CoB_BK7231N_6-Outlet_Powerstrip_with_Energy_Monitoring"
  project_version: "0.0.1"
  hardware_info: "Tuya Generic Custom CoB BK7231N 6 Outlet Powerstrip with Energy Monitoring"
  restore_mode_relay1: RESTORE_DEFAULT_ON
  restore_mode_relay2: RESTORE_DEFAULT_ON
  restore_mode_relay3: RESTORE_DEFAULT_ON
  restore_mode_relay4: RESTORE_DEFAULT_ON
  restore_mode_relay5: RESTORE_DEFAULT_ON
  restore_mode_relay6: RESTORE_DEFAULT_ON
  restore_mode_relayUSB: ALWAYS_ON

bk72xx:
  board: generic-bk7231n-qfn32-tuya

packages:
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

switch:
  - platform: gpio
    id: switch_1
    name: Outlet 1
    pin: P7
    restore_mode: ${restore_mode_relay1}
  - platform: gpio
    id: switch_2
    name: Outlet 2
    pin: P26
    restore_mode: ${restore_mode_relay2}
  - platform: gpio
    id: switch_3
    name: Outlet 3
    pin: P14
    restore_mode: ${restore_mode_relay3}
  - platform: gpio
    id: switch_4
    name: Outlet 4
    pin: P9
    restore_mode: ${restore_mode_relay4}
  - platform: gpio
    id: switch_5
    name: Outlet 5
    pin: P24
    restore_mode: ${restore_mode_relay5}
  - platform: gpio
    id: switch_6
    name: Outlet 6
    pin: P22
    restore_mode: ${restore_mode_relay6}
  - platform: gpio
    id: switch_7
    name: Outlet USB
    pin: P6
    restore_mode: ${restore_mode_relayUSB}

binary_sensor:
  - platform: gpio
    id: binary_switch_all
    pin:
      number: P8
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
        - switch.toggle: switch_2
        - switch.toggle: switch_3
        - switch.toggle: switch_4
        - switch.toggle: switch_5
        - switch.toggle: switch_6
        - switch.toggle: switch_7

status_led:
  pin: P23

uart:
  id: uart_bus
  tx_pin: TX1
  rx_pin: RX1
  baud_rate: 4800
  stop_bits: 1

sensor:
  - platform: bl0942
    uart_id: uart_bus
    current:
      name: BL0942 Current
    voltage:
      name: BL0942 Voltage
    power:
      name: BL0942 Power
      filters:
        multiply: -1
    energy:
      name: BL0942 Energy
    frequency:
      name: BL0942 Frequency
      accuracy_decimals: 2
