substitutions:
  project_name: "Bubble.RGB_Lamp"
  project_version: "0.0.1"
  hardware_info: "Bubble RGB Lamp"

esp8266:
  board: esp_wroom_02
  restore_from_flash: true

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  web_controls_rgb: !include ../../web-controls/rgb.yaml
  web_controls_cct: !include ../../web-controls/cct.yaml

logger:
  baud_rate: 0

# uart:
#   rx_pin: GPIO3
#   tx_pin: GPIO1
#   baud_rate: 9600

light:
  - platform: rgb
    id: rgb_light
    name: ${friendly_name}
    red: output_red
    green: output_green
    blue: output_blue

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14

status_led:
  pin:
    number: GPIO5

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    id: power_button
    on_press:
      light.toggle: rgb_light
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
    id: wifi_button
    on_press:
      light.toggle: rgb_light
