rtl87xx:
  board: generic-rtl8710bn-2mb-788k # T103_V1.0 ESP12S layout clone
  framework:
    #version: "1.5.1"
    version: "0.0.0"
    source: "https://github.com/libretiny-eu/libretiny#feature/i2c-spi"

#packages:
  # rgb_control: !include ../../web-controls/rgb.yaml

api:
  reboot_timeout: 0s

binary_sensor:
  - platform: gpio
    id: button_1
    pin: PA12
  - platform: gpio
    id: button_2
    pin: PA05
  - platform: gpio
    id: button_3
    pin: PA00

# IR Pin PA14

# spi:
#   interface: software
#   clk_pin: PA18
#   mosi_pin: PA23 # PA23
#   #miso_pin: PA22
  

# light:
#   - platform: spi_led_strip
#     num_leds: 48
#     #color_correct: [80%, 60%, 100%]
#     id: light_primary
#     name: "RGB LED Strip"
#     #data_rate: 1MHz

# light:
#   - platform: fastled_clockless
#     chipset: WS2811
#     pin: PA23
#     num_leds: 48
#     rgb_order: RGB
#     name: "FastLED WS2811 Light"

# light:
#   - platform: neopixelbus
#     id: light_primary
#     type: RGB
#     variant: WS2811
#     pin: PA23
#     num_leds: 48
#     name: "NeoPixel Light"

external_components:
  - source:
        type: local
        path: custom_components
    components: [ spi ]

# spi:
#   mosi_pin: GPIO23
#   clk_pin: GPIO18

# light:
#   - platform: spi_led_strip
#     num_leds: 48
#     id: rgb_led
#     name: "RGB LED Strip"
#     data_rate: 1MHz
