substitutions:
  project_name: "Onforu.90W_PWM_RGBWW_Spotlight"
  project_version: "0.0.1"
  hardware_info: "Onforu 90W PWM RGBWW Spotlight"

bk72xx:
  board: cbu

packages:
  rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml
  ddp: !include ../../ddp/ddp.yaml

output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIOWM4
  - platform: libretiny_pwm
    id: output_green
    pin: GPIOWM2
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIOWM1
  - platform: libretiny_pwm
    id: output_warm_white
    pin: GPIOWM0
  - platform: libretiny_pwm
    id: output_cold_white
    pin: GPIOWM5

light:
  - id: !extend light_primary
    effects:
      - ddp
