substitutions:
  project_name: "Onforu.25W_PWM_RGBWW_Spotlight"
  project_version: "0.0.1"
  hardware_info: "Onforu 25W PWM RGBWW Spotlight"

bk72xx:
  board: cbu

packages:
  rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml
  ddp: !include ../../ddp/ddp.yaml

output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIO24
  - platform: libretiny_pwm
    id: output_green
    pin: GPIO8
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIO7
  - platform: libretiny_pwm
    id: output_warm_white
    pin: GPIO6
  - platform: libretiny_pwm
    id: output_cold_white
    pin: GPIO26

light:
  - id: !extend light_primary
    effects:
      - ddp
