substitutions:
  restore_mode_light: RESTORE_DEFAULT_OFF
  default_white_color_temperature: "2700 K"

packages:
  web_controls_rgb: !include ../web-controls/rgb.yaml

light:
  - platform: rgbw
    restore_mode: ${restore_mode_light}
    id: light_primary
    name: ""
    color_interlock: true
    red: output_red
    green: output_green
    blue: output_blue
    white: output_warm_white

# On boot, if all colors and whites are set to full (defult unset), set default to warm white
esphome:
  on_boot:
    if:
      condition:
        lambda: return id(light_primary).current_values.get_red() == 1.0f && id(light_primary).current_values.get_green() == 1.0f && id(light_primary).current_values.get_blue() == 1.0f && (id(light_primary).current_values.get_cold_white() == 1.0f || id(light_primary).current_values.get_warm_white() == 1.0f);
      then:
        light.control:
          id: light_primary
          red: 0%
          green: 0%
          blue: 0%
          color_brightness: 0%
          color_temperature: ${default_white_color_temperature}
          brightness: 100%
          # cold_white: 0%
          # warm_white: 100%
