substitutions:
  project_name: "Tuya_Generic.MSL12_WB8_RGBIC_Fairy_Light_Strip"
  project_version: "0.0.1"
  hardware_info: "Tuya Generic MSL12 WB8 RGBIC Fairy Light Strip"

bk72xx:
  board: generic-bk7231t-qfn32-tuya # WB8, looks just like WB3S, but WB3S doesn't have GPIO16

packages:
  lt_beken_source: !include ../../beken/lt-beken-source.yaml
  #ddp: !include ../../ddp/ddp.yaml

light:
  - platform: beken_spi_led_strip
    rgb_order: RGB
    pin: GPIO16
    num_leds: 90
    #chipset: ws2812
    #chipset: sk6812
    #chipset: apa106
    chipset: sm16703
    name: None

remote_receiver:
  pin: GPIO26
  dump: all

# mic on P23?

binary_sensor:
  - platform: gpio
    id: button_on_off
    pin: 
      number: GPIO24
      inverted: true
  - platform: gpio
    id: button_music
    pin: 
      number: GPIO7
      inverted: true
  - platform: gpio
    id: button_color
    pin: 
      number: GPIO9
      inverted: true
