substitutions:
  project_name: "Tuya_Generic.WB8_RGBIC_Fairy_Light_Strip"
  project_version: "0.0.1"
  hardware_info: "Tuya Generic WB8 RGBIC Fairy Light Strip"

bk72xx:
  board: wb3s # WB8, looks just like WB3S

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  #rgbww_light: !include ../../light/rgbww.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml
  #ddp: !include ../../ddp/ddp.yaml
