substitutions:
  project_name: "Moes.CBU_4_Button_Scene_Switch"
  project_version: "0.0.1"
  hardware_info: "Moes CB2S Toggle Switch"
  restore_mode_relay1: ALWAYS_OFF
  restore_mode_relay2: ALWAYS_OFF
  restore_mode_relay3: ALWAYS_OFF
  restore_mode_relay4: ALWAYS_OFF

bk72xx:
  board: cbu

packages:
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

output:
  - platform: gpio
    id: output_led_1
    pin:
      number: GPIO14
      inverted: true
  - platform: gpio
    id: output_led_2
    pin:
      number: GPIO16
      inverted: true
  - platform: gpio
    id: output_led_3
    pin:
      number: GPIO20
      inverted: true
  - platform: gpio
    id: output_led_4
    pin:
      number: GPIO22
      inverted: true

light:
  - platform: binary
    id: light_switch_1
    output: output_led_1
  - platform: binary
    id: light_switch_2
    output: output_led_2
  - platform: binary
    id: light_switch_3
    output: output_led_3
  - platform: binary
    id: light_switch_4
    output: output_led_4

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: GPIO23
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
  - platform: gpio
    id: binary_switch_2
    pin:
      number: GPIO9
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_2
  - platform: gpio
    id: binary_switch_3
    pin:
      number: GPIO28
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_3
  - platform: gpio
    id: binary_switch_4
    pin:
      number: GPIO8
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_4

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: GPIO24
    restore_mode: ${restore_mode_relay1}
    on_turn_on:
      - light.turn_on: light_switch_1
    on_turn_off:
      - light.turn_off: light_switch_1
  - platform: gpio
    id: switch_2
    name: Relay 2
    pin: GPIO26
    restore_mode: ${restore_mode_relay2}
    on_turn_on:
      - light.turn_on: light_switch_2
    on_turn_off:
      - light.turn_off: light_switch_2
  - platform: gpio
    id: switch_3
    name: Relay 3
    pin: GPIO6
    restore_mode: ${restore_mode_relay3}
    on_turn_on:
      - light.turn_on: light_switch_3
    on_turn_off:
      - light.turn_off: light_switch_3
  - platform: gpio
    id: switch_4
    name: Relay 4
    pin: GPIO7
    restore_mode: ${restore_mode_relay4}
    on_turn_on:
      - light.turn_on: light_switch_4
    on_turn_off:
      - light.turn_off: light_switch_4
