substitutions:
  project_name: "CloudFree/Milfra.SWM1/MFA05_ESP8266_1_Button_Motion_Switch"
  project_version: "0.0.1"
  hardware_info: "CloudFree/Milfra SWM1/MFA05 ESP8266 1 Button Motion Switch"
  restore_mode_relay: ALWAYS_ON
  restore_mode_motion: RESTORE_DEFAULT_ON

esp8266:
  board: esp8285
  restore_from_flash: true
  early_pin_init: false

packages:
  dummy_light: !include ../../light/dummy-light.yaml
  motion_scripts: !include
    file: ../../motion/motion-scripts.yaml
    vars:
      target_light: light_primary

light: 
  - platform: status_led
    id: light_status
    pin:
      # Blue LED
      number: GPIO13
      inverted: true

# The green LED appears to mask the blue 
# It also appears to be overridden by the relay
output:
  - platform: gpio
    # Green LED
    id: led1
    pin: GPIO16
        
switch:
  - platform: gpio
    name: "Load Power"
    id: load_power
    entity_category: config
    restore_mode: ${restore_mode_relay}
    pin: GPIO12
  - platform: template
    id: motion_enabled
    name: "Motion Enabled"
    entity_category: config
    icon: "mdi:motion-sensor"
    optimistic: true
    restore_mode: ${restore_mode_motion}

binary_sensor:
  - platform: gpio
    id: button_toggle
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_click:
      if:
        condition:
          light.is_off: light_primary
        then:
          - light.turn_on: light_primary
          - lambda: id(motion_activated) = 0;
        else:
          - light.turn_off: light_primary
  - platform: gpio
    id: motion_primary
    name: "Motion Sense"
    device_class: "motion"
    icon: "mdi:motion-sensor"
    pin:
      number: GPIO5
      inverted: true
      mode: INPUT_PULLUP
  - platform: gpio
    id: light_sense_state
    name: "Light Sense"
    device_class: "light"
    icon: "mdi:theme-light-dark"
    pin:
      number: GPIO14
      mode: INPUT
