substitutions:
  project_name: "Qiachip.CBU_Relay_Switch"
  project_version: "0.0.1"
  hardware_info: "Qiachip CBU Relay Switch"

bk72xx:
  board: cb2s

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

binary_sensor:
  - platform: gpio
    id: button_toggle
    pin:
      number: GPIO7
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: "Relay"
    pin: GPIO8
    on_turn_on:
      switch.turn_on: led_status
    on_turn_off:
      switch.turn_off: led_status
  - platform: gpio
    id: led_status
    pin:
      number: GPIO10
      inverted: true

# status_led:
#   pin:
#     number: GPIO10
#     inverted: true
