substitutions:
  project_name: "Tuya_Generic.YX-WS003_CBU_3_Button_Switch"
  project_version: "0.0.1"
  hardware_info: "Tuya Generic YX-WS003 CBU 3 Button Switch"
  restore_mode_relay1: ALWAYS_OFF
  restore_mode_relay2: ALWAYS_OFF
  restore_mode_relay3: ALWAYS_OFF

bk72xx:
  board: cbu

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

output:
  - platform: gpio
    id: output_led_1
    pin: GPIO20
  - platform: gpio
    id: output_led_2
    pin: GPIO8
  - platform: gpio
    id: output_led_3
    pin: GPIO28

light:
  - platform: binary
    id: led_1
    output: output_led_1
  - platform: binary
    id: led_2
    output: output_led_2
  - platform: binary
    id: led_3
    output: output_led_3

binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: GPIO14
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
  - platform: gpio
    id: button_2
    pin:
      number: GPIO16
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_2
  - platform: gpio
    id: button_3
    pin:
      number: GPIO9
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_3

switch:
  - platform: gpio
    id: relay_1
    name: Relay 1
    pin: GPIO6
    restore_mode: ${restore_mode_relay1}
    on_turn_on:
      - light.turn_on: led_1
    on_turn_off:
      - light.turn_off: led_1
  - platform: gpio
    id: relay_2
    name: Relay 2
    pin: GPIO26
    restore_mode: ${restore_mode_relay2}
    on_turn_on:
      - light.turn_on: led_2
    on_turn_off:
      - light.turn_off: led_2
  - platform: gpio
    id: relay_3
    name: Relay 3
    pin: GPIO24
    restore_mode: ${restore_mode_relay3}
    on_turn_on:
      - light.turn_on: led_3
    on_turn_off:
      - light.turn_off: led_3
