substitutions:
  project_name: "Emporia.ESP32_Vue_3"
  project_version: "0.0.1"
  hardware_info: "Emporia ESP32 Vue 3"

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue

esp32:
  board: esp32dev
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended

preferences:
  # please also make sure `restore: false` is set on all `platform: total_daily_energy`
  # sensors below.
  flash_write_interval: "48h"

# Enable Home Assistant API
api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

output:
  - platform: ledc
    pin:
      number: GPIO12
      ignore_strapping_warning: true
    id: buzzer
  - platform: gpio
    pin: GPIO27
    id: buzzer_gnd

rtttl:
  output: buzzer
  on_finished_playback:
    - logger.log: 'Song ended!'

button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

status_led:
  pin:
    number: GPIO2
    ignore_strapping_warning: true

light:
  - platform: status_led
    id: led_ethernet
    pin: GPIO4
    #restore_mode: ALWAYS_ON
    #entity_category: config

i2c:
  sda:
    number: GPIO5
    ignore_strapping_warning: true
  scl: 18
  scan: false
  frequency: 400kHz
  timeout: 1ms
  id: i2c_a
