substitutions:
  project_name: "Tuya_Generic.CBU_PIR_Lux_Sensor"
  project_version: "0.0.1"
  hardware_info: "Tuya Generic CBU PIR Lux Sensor"

bk72xx:
  board: cbu

packages:
  device_diagnostics: !include ../device-diagnostics.yaml
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

# GPIO24 - Reset Button (inverted)
# GPIO8 - PIR Motion Sense State

binary_sensor:
  - platform: gpio
    name: Reset Button
    pin:
      number: GPIO24
      inverted: true
  - platform: gpio
    name: GPIO26
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
  - platform: gpio
    name: GPIO14
    pin: GPIO14
  - platform: gpio
    name: GPIO16
    pin: GPIO16
  - platform: gpio
    name: GPIO20
    pin: GPIO20
  - platform: gpio
    name: GPIO22
    pin: GPIO22
  - platform: gpio
    name: GPIO1
    pin: GPIO1
  - platform: gpio
    name: GPIO0
    pin: GPIO0
  - platform: gpio
    name: GPIO6
    pin:
      number: GPIO6
      mode: INPUT_PULLUP
  - platform: gpio
    name: GPIO7
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
  - platform: gpio
    name: Motion Sense
    pin: GPIO8
  - platform: gpio
    name: GPIO10
    pin: GPIO10
  - platform: gpio
    name: GPIO11
    pin: GPIO11
  - platform: gpio
    name: GPIO28
    pin: GPIO28
  - platform: gpio
    name: GPIO9
    pin: GPIO9
  - platform: gpio
    name: GPIO17
    pin: GPIO17
  - platform: gpio
    name: GPIO15
    pin: GPIO15

sensor:
  - platform: adc
    pin: ADC3
    name: ADC
    update_interval: 30min