substitutions:
  project_name: "Tuya_Generic.CBU_809WT_PIR_Alarm"
  project_version: "0.0.1"
  hardware_info: "Tuya Generic CBU 809WT PIR Lux Sensor"

packages:
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

bk72xx:
  board: cbu

# GPIO14 - Reset Button (inverted)
# GPIO16 must be high for button to work?
# GPIO8 - PIR Motion Sense State
# GPIO20 - Red LED
# GPIO22 - Changes ADC value (2.048V when off, 1.338-1.348 when on) (activate battery check?)
# GPIO23 ADC - 2.048V when P22 is Off, monitors voltage when P22 on (1.33-1.34V when USB)
# Traces to GPIO0 & GPIO16
# Lux back to P26/P6/P7, P6 may be dead-ended
# |- could be i2c?

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true

switch:
  - platform: gpio
    id: GPIO16
    pin: GPIO16
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: GPIO0
    pin: GPIO0
  - platform: gpio
    name: GPIO22
    pin: GPIO22
  # - platform: gpio
  #   name: GPIO6
  #   pin:
  #     number: GPIO6
  #     mode: INPUT_PULLUP
  # - platform: gpio
  #   name: GPIO7
  #   pin:
  #     number: GPIO7
  #     mode: INPUT_PULLUP
  # - platform: gpio
  #   name: GPIO26
  #   pin:
  #     number: GPIO26
  #     mode: INPUT_PULLUP

button:
  - platform: template
    id: play_rtttl
    name: rtttl play
    on_press:
      - rtttl.play:
          rtttl: !lambda 'return "mario:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,16p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16c7,16p,16c7,16c7,p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16d#6,8p,16d6,8p,16c6";'

status_led:
  pin:
    mode: INPUT_PULLUP
    number: GPIO20
    inverted: true

sensor:
  - platform: adc
    pin: GPIO23
    name: ADC
    update_interval: 2s

output:
  - platform: libretiny_pwm
    id: rtttl_out
    pin: GPIO6

rtttl:
  output: rtttl_out
  id: my_rtttl
  #gain: 60%
