substitutions:
  devicename: humidifier

esphome:
  name: humidifier

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
ota:
web_server:
time:
  - platform: sntp
    id: the_time
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret wifi_ap_password
captive_portal:

#debug:
#  update_interval: 5s

#text_sensor:
#  - platform: debug
#    device:
#      name: "Device Info"

#sensor:
#  - platform: debug
#    free:
#      name: "Heap Free"
##    fragmentation:
##      name: "Heap Fragmentation"
#    block:
#      name: "Heap Max Block"
#    loop_time:
#      name: "Loop Time"

#GPIO14 - float
#GPIO27 - front button press
#GPIO5 - Sensor by fan 1/3
#GPIO0 - Sensor by fan 2/3
#GPIO18 - Sensor by fan 3/3
#25,26,33 - fan states low/med/high
#34/35/en unknown
#13/15 (bottom) unknown
#19 unknown
#21/22/23 unknown
#speaker in the 19-23 range?

#Handled:
##GPIO17 - LED_1
##GPIO16 - LED_2
##GPIO4 - LED_3

#WARNING GPIO0 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#WARNING GPIO2 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#WARNING GPIO4 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#WARNING Pin 9 (9-10) might already be used by the flash interface in QUAD IO flash mode.
#WARNING Pin 10 (9-10) might already be used by the flash interface in QUAD IO flash mode.
#WARNING GPIO12 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#WARNING GPIO15 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#WARNING GPIO0 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#ARNING GPIO2 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#WARNING GPIO4 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#WARNING Pin 9 (9-10) might already be used by the flash interface in QUAD IO flash mode.
#WARNING Pin 10 (9-10) might already be used by the flash interface in QUAD IO flash mode.
#WARNING GPIO12 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
#WARNING GPIO15 is a Strapping PIN and should be avoided.
#Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
#See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins

switch:
#  - platform: gpio
#    pin: 27
#    id: humidifier_button
#    name: "Humidifier Button"
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: humidifier_button
  - platform: gpio
    pin: 25
    id: relay_fan_1
    name: "relay_fan_1"
  - platform: gpio
    pin: 26
    id: relay_fan_2
    name: "relay_fan_2"
  - platform: gpio
    pin: 33
    id: relay_fan_3
    name: "relay_fan_3"
  # - platform: template
  #   id: update_fan_speed
  #   optimistic: True
  #   turn_on_action:
  #     then:
  #       #- delay: 200ms
  #       - if:
  #           condition:
  #             and:
  #               - switch.is_off: relay_fan_1
  #               - switch.is_off: relay_fan_2
  #               - switch.is_off: relay_fan_3
  #           then:
  #             - fan.turn_off: fan_1
  #       - if:
  #           condition:
  #             and:
  #               - switch.is_on: relay_fan_1
  #               - switch.is_off: relay_fan_2
  #               - switch.is_off: relay_fan_3
  #           then:
  #             - fan.turn_on:
  #                 id: fan_1
  #                 speed: 1
  #       - if:
  #           condition:
  #             and:
  #               - switch.is_on: relay_fan_1
  #               - switch.is_on: relay_fan_2
  #               - switch.is_off: relay_fan_3
  #           then:
  #             - fan.turn_on:
  #                 id: fan_1
  #                 speed: 2
  #       - if:
  #           condition:
  #             and:
  #               - switch.is_on: relay_fan_1
  #               - switch.is_off: relay_fan_2
  #               - switch.is_on: relay_fan_3
  #           then:
  #             - fan.turn_on:
  #                 id: fan_1
  #                 speed: 3

#binary_sensor:
#GPIO14 constantly switching on/off
#  - platform: gpio
#    pin: GPIO14
#    name: "Pin GPIO14"
#GPIO27 constantly switching on/off
#  - platform: gpio
#    pin: GPIO27
#    name: "Pin GPIO27"


light:
  - platform: rgb
    name: "Humidifier Light"
    red: output_redled
    green: output_greenled
    blue: output_blueled

# Example output entry
output:
  - platform: ledc
    id: output_redled
    pin: GPIO4
  - platform: ledc
    id: output_greenled
    pin: GPIO17
  - platform: ledc
    id: output_blueled
    pin: GPIO16
#  - platform: gpio
#    pin: GPIO27
#    id: output_button
#  - platform: gpio
#    pin: GPIO27
#    id: GPIO27_output
  # - platform: template
  #   id: fan_speed
  #   type: float
  #   write_action:
  #     - then:
  #       - if:
  #           condition:
  #             lambda: return ((state > 0) && (state < .4));
  #           then:
  #             - switch.turn_on: relay_fan_1
  #             #- delay: 20ms
  #             - switch.turn_off: relay_fan_2
  #             #- delay: 20ms
  #             - switch.turn_on: relay_fan_3
  #       - if:
  #           condition:
  #             lambda: return ((state > .4) && (state < .7));
  #           then:
  #             - switch.turn_off: relay_fan_1
  #             #- delay: 20ms
  #             - switch.turn_on: relay_fan_2
  #             #- delay: 20ms
  #             - switch.turn_on: relay_fan_3
  #       - if:
  #           condition:
  #             lambda: return (state > .7);
  #           then:
  #             - switch.turn_on: relay_fan_1
  #             #- delay: 20ms
  #             - switch.turn_on: relay_fan_2
  #             #- delay: 20ms
  #             - switch.turn_on: relay_fan_3
  #       - if:
  #           condition:
  #             lambda: return (state < 0.01);
  #           then:
  #             - switch.turn_off: relay_fan_1
  #             #- delay: 20ms
  #             - switch.turn_off: relay_fan_2
  #             #- delay: 20ms
  #             - switch.turn_off: relay_fan_3

#sensor:
#  - platform: esp32_hall
#    name: "Humidifier Hall Sensor"
#    update_interval: 1s

#esp32_touch:
#  setup_mode: false

#binary_sensor:
#  - platform: esp32_touch
#    name: "ESP32 Touch Pad GPIO27"
#    pin: GPIO27
#    threshold: 1000
binary_sensor:
  # - platform: gpio
  #   pin: GPIO27
  #   id: gpio27
  #   name: "gpio27"
  - platform: gpio
    pin: GPIO14
    id: gpio14
    name: "gpio14"
  - platform: gpio
    pin: GPIO5
    id: gpio5
    name: "gpio5"
  - platform: gpio
    pin: GPIO0
    id: gpio0
    name: "gpio0"
  - platform: gpio
    pin: GPIO18
    id: gpio18
    name: "gpio18"
  - platform: gpio
    pin: GPIO34
    id: gpio34
    name: "gpio34"
  - platform: gpio
    pin: GPIO35
    id: gpio35
    name: "gpio35"
  - platform: gpio
    pin: GPIO13
    id: gpio13
    name: "gpio13"
  - platform: gpio
    pin: GPIO15
    id: gpio15
    name: "gpio15"
  - platform: gpio
    pin: GPIO19
    id: gpio19
    name: "gpio19"

# fan:
#   - platform: speed
#     id: fan_1
#     output: fan_speed
#     name: ${friendly_name} Fan Speed
#     speed_count: 3

#GPIO14 - float
#GPIO27 - front button press
#GPIO5 - Sensor by fan 1/3
#GPIO0 - Sensor by fan 2/3
#GPIO18 - Sensor by fan 3/3
#25,26,33 - fan states low/med/high
#34/35/en unknown
#13/15 (bottom) unknown
#19 unknown
#21/22/23 unknown
#speaker in the 19-23 range?

#Handled:
##GPIO17 - LED_1
##GPIO16 - LED_2
##GPIO4 - LED_3

# output:
#   - platform: template
#     id: fan_output
#     type: float
#     write_action:
#       - if:
#           condition:
#             lambda: return (state < .3);
#           then:
#             - switch.turn_off: mode1
#             - switch.turn_off: mode2
#             - switch.turn_off: relay
#       - if:
#           condition:
#             lambda: return ((state > 0) && (state < .4));
#           then:
#             - switch.turn_on: mode1
#             - switch.turn_off: mode2
#             - switch.turn_on: relay
#       - if:
#           condition:
#             lambda: return ((state > 0.4) && (state < .7));
#           then:
#             - switch.turn_off: mode1
#             - switch.turn_on: mode2
#             - switch.turn_on: relay
#       - if:
#           condition:
#             lambda: return (state > 0.7);
#           then:
#             - switch.turn_on: mode1
#             - switch.turn_on: mode2
#             - switch.turn_on: relay
            
# fan:
#   - platform: speed
#     output: fan_output
#     name: "$devicename fan"
#     id: humidifier
#     speed_count: 3
    
# binary_sensor:
#   - platform: gpio
#     pin:
#       number: GPIO27
#       #inverted: True
#     filters:
#       - delayed_on_off: 50ms
#     name: "$devicename button"
#     on_click:
#       then:
#         - if:
#             condition:
#               and:
#                 - switch.is_on: mode1
#                 - switch.is_on: mode2
#             then:
#               - fan.turn_off: humidifier
#         - if:
#             condition:
#               and:
#                 - switch.is_off: mode1
#                 - switch.is_off: mode2
#             then:
#               - fan.turn_on:
#                   id: humidifier
#                   #speed: LOW
#                   speed: 1
#         - if:
#             condition:
#               and:
#                 - switch.is_on: mode1
#                 - switch.is_off: mode2
#             then:
#               - fan.turn_on:
#                   id: humidifier
#                   #speed: MEDIUM
#                   speed: 2
#         - if:
#             condition:
#               and:
#                 - switch.is_off: mode1
#                 - switch.is_on: mode2
#             then:
#               - fan.turn_on:
#                   id: humidifier
#                   #speed: HIGH
#                   speed: 3
#   - platform: gpio
#     pin:
#       number: GPIO5
#       mode: INPUT_PULLUP
#     filters:
#       - delayed_on_off: 100ms
#     name: "$devicename thirst"
#     on_press:
#       - output.turn_off: fan_output
#   - platform: gpio
#     pin:
#       number: GPIO14
#       mode: INPUT_PULLUP
#       inverted: True
#     filters:
#       - delayed_on_off: 100ms
#     name: "$devicename water"
#     on_press:
#       - output.turn_off: fan_output
    
# switch:
#   - platform: gpio
#     pin:
#       number: GPIO25
#     restore_mode: RESTORE_DEFAULT_OFF
#     id: relay
#     internal: true
#   - platform: gpio
#     id: mode1
#     pin:
#       number: GPIO26
#       #inverted: True
#     restore_mode: RESTORE_DEFAULT_OFF
#     internal: true
#   - platform: gpio
#     id: mode2
#     pin:
#       number: GPIO33
#       #inverted: True
#     restore_mode: RESTORE_DEFAULT_OFF
#     internal: true