substitutions:
  project_name: "Tuya_Generic.WB3S_BL-XK01_Star_Projector"
  project_version: "0.0.1"
  hardware_info: "Tuya Generic WB3S BL-XK01 Star Projector"

packages:
  lt_beken_source: !include ../../beken/lt-beken-source.yaml

bk72xx:
  board: wb3s

output:
  - platform: libretiny_pwm
    id: output_red
    pin: GPIO9
  - platform: libretiny_pwm
    id: output_green
    pin: GPIO24
  - platform: libretiny_pwm
    id: output_blue
    pin: GPIO26
  - platform: libretiny_pwm
    id: output_cold
    pin: GPIO8

light:
  - platform: rgbw
    id: light_rgbw
    name: Light
    red: output_red
    green: output_green
    blue: output_blue
    white: output_cold
